name: EliteModels
version: '1.0-SNAPSHOT'
main: com.lolivetgt.elitemodels.EliteModels
api-version: 1.19
authors: [Luis Olivet]
description: Dale vida a los mobs personalizados de Minecraft java Vanilla,
commands:
  elitemodels:
    description: Sistema de Model 3D para Minecraft.
    permission-message: No tenes permisos para usar este comando.
    usage: /elitemodels <reload|reload models|reload config|version|zip>
  emd:
    description: Sistema de Model 3D para Minecraft.
    permission-message: No tenes permisos para usar este comando.
    usage: /emd <reload|reload models|reload config|version|zip>